### ISSUE TITLE
Implement system for DOM events handling

### ISSUE THREAD

**Issue by dfilatov** [dfilatov/vidom#10]

**Comment by dfilatov** [comment]
closed via d27fa51b8cda45a2f4468e53db14b26f4233213a

**Comment by gaydenko** [comment]
@dfilatov , does it mean the main functionality is already in the box? :)

**Comment by dfilatov** [comment]
@gaydenko No, it doesn't, sorry. I don't want to be bound by any restrictions on such an early phase of development.

**Comment by gaydenko** [comment]
@dfilatov , no-no, I don't mean any bounds! I mean quite an opposite - some low limit was overcome :) That is, to my taste, working with virtual DOM itself (building, mounting,..), lifecycle tracking and dealing with DOM events compose a minimum to be useful.
