### ISSUE TITLE
[URGENT] children issues

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#100]
Hi. If you have one child and plain text, everything is okey. But soon as you do this:

``` .children[new TagNode("div"), "fooBar"]```

This will throw. So atm. you can't have a text node in an array as you had before.

And you can't swap a text child with another child.

And maybe you should consider to use ``` node.firstChild.nodeValue ``` where you can as an replacement for ```textContent``` because it's much faster.

**Comment by rickardjanson** [comment]
@dfilatov  If you in the iteration loop in the `renderToDom()` function checks if it's a text string, it will work. But you got more issues. Let say you have this:

``` var a = new TagNode("div").children( [new TagNode("span"), "Hello, World!!"]);```

The result here will be that the text on the `div` node will be `Hello World`, but the `span tag` will never show up. Vanished.

Same seems to happen in your diffing & patching algorithm. The text will be set, but not other children if it's an array.

I didn't investigate further, but seems to be other problems as well related to this.

**Comment by rickardjanson** [comment]
@dfilatov I think I know what's causing this. See the patching algorithm. You dealing with text, and take a quick return if it's text child without processing the other children.

**Comment by rickardjanson** [comment]
I'm closer to a solution. Again this example: 

 ``` var a = new TagNode("div").children( [new TagNode("span"), "Hello, World!!"]);``` 

The span will vanish. Not patched. Hower, try to do this;

 ``` var a = new TagNode("div").children( ["Hello, World!!", new TagNode("span")]);``` 

Now you will see that both the text and the span tags are there. Why? I did it in reverse order in the array.

And again now, when I mention reverse order, I reference to my other issue ticket:  https://github.com/dfilatov/vidom/issues/101

**Comment by dfilatov** [comment]
Right now it's not allowed to use plain text as element of children array. We have discussed it in #75

**Comment by rickardjanson** [comment]
@dfilatov I know that.  At that time you could do new TextNode and still use text in arrays. That option are now removed and you can only use text as a single child only.

Before you could have multiple tags and text in one array. Anyhow now this fuck up your patching algorithm

**Comment by dfilatov** [comment]
> Before you could have multiple tags and text in one array.
No, you couldn't.

**Comment by rickardjanson** [comment]
@dfilatov before you could ``` [ new textnode ("a"), new TextNode (b)  ]   ``` . Multiple text in one array. This is taken away now so only one single node as text

**Comment by dfilatov** [comment]
Yes, now you have to wrap your text nodes.

**Comment by rickardjanson** [comment]
@dfilatov  In the future, will it be fixed so you don't have to wrap the text nodes? This is the first lVD  library I experience this one. Compare to others.

Have you studied `ReactText`. That is how React solve this issue etc.

**Comment by dfilatov** [comment]
React wraps all text nodes in span tags except the case when a text node is only child.
