### ISSUE TITLE
Reverse and removeLast higher numbers then before in benchmark

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#101]
If you compare with your previous solution, against the new changes you did. You will see that the `reverse` in the benchmark are higher now then before.
Example:
```
[500] ["reverse"] render()	608
[500] ["reverse"] update()	748
```
There are here a difference around 140. In  your previous solution, this two had almost identical values. Why did this increase with over 140 ??
Also this:
```
[10,10,5] ["reverse","skip","skip"] render()
```
are over 100 higher then before.
And also ```insertLast``` have a 100 in difference compared to your solution before.

Same aslo with  ```moveFromEndToStart ```

Should you optimize this?? 

Also everything related to ```shuffle``` have higher values now then before.

**Comment by dfilatov** [comment]
Unfortunately It's hard to trust results of "vdom-bencmark", they change from run to run, they depend on which test is runned first and many other unpredictable factors.
For example, here is my result:
![](https://img-fotki.yandex.ru/get/6834/58414218.1/0_ea18f_f2d50a24_orig)

**Comment by dfilatov** [comment]
As you see, almost everything is better in 0.0.21
