### ISSUE TITLE
Any plans to integrate...

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#104]
Any plans to integrate...

1. Reusable components
2. XHR aka AJAX
3. Two-way binding
4. forms
5. query aka REACT-query - https://github.com/elierotenberg/react-query
6. CSS transitions . E.g.  https://facebook.github.io/react/docs/animation.html#high-level-api-reactcsstransitiongroup
7.  Routing. E.g. https://github.com/rackt/react-router

**Comment by dfilatov** [comment]
Reusable components are already integrated in vidom.
What about other things you mentioned, I'm not going to build a monster which can do everything. All these could be and must be implemented as separate projects, not here, not in core.

**Comment by rickardjanson** [comment]
Two-way binding has to be part of the core itself, hasn't it?

**Comment by dfilatov** [comment]
It depends on what you mean by two-way binding. Moreover, two-way binding is root of evil )

**Comment by rickardjanson** [comment]
"Two-way binding means that any data-related changes affecting the model are immediately propagated to the matching view(s), and that any changes made in the view(s) (say, by the user) are immediately reflected in the underlying model. When app data changes, so does the UI, and conversely.

This is a very solid concept to build a web application on top of, because it makes the "Model" abstraction a safe, atomic data source to use everywhere within the application. Say, if a model, bound to a view, changes, then its matching piece of UI (the view) will reflect that, no matter what. And the matching piece of UI (the view) can safely be used as a mean of collecting user inputs/data, so as to maintain the application data up-to-date.

A good two-way binding implementation should obviously make this connection between a model and some view(s) as simple as possible, from a developper point of view.*"

**Comment by dfilatov** [comment]
Better take a look at patterns which provide unidirectional data flow.

**Comment by rickardjanson** [comment]
Flux? Or a similar solution from scratch?

**Comment by dfilatov** [comment]
Yes, Flux is one of the most popular buzzword.

**Comment by gaydenko** [comment]
Just want to mention, Flux and, say, inspired Redux are treated by some developers as the next pointless hype to sell being not suitable for real applications :) As for two way binding, yes, at those rare cases it is needed it can be easy implemented outside the virtual DOM library the way is appropriate to the application in hand and developer's taste.

**Comment by dfilatov** [comment]
I have cited Flux just as an example. Unidirectional data flow pattern had existed before even facebook was founded )

**Comment by gaydenko** [comment]
@dfilatov , I see :)
