### ISSUE TITLE
innerHTML not correct in SSR

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#105]
`innerHTML` are not set correct in SSR. Your script only put them as literal attributes, but it's content should be the text content.

``` createNode("div").attrs({"innerHTML" : "123" }).renderToString() ```

Result:  ``` <div innerHTML="123"></div>  ```
Expected result: ``` <div>123</div>  ```

**Comment by dfilatov** [comment]
You have to use `html()` method to insert unescaped html instead of using i`nnerHTML` property.

**Comment by rickardjanson** [comment]
@dfilatov Shouldn't the same method be inside ComponentNode?

**Comment by dfilatov** [comment]
No, it shouldn't be there.
