### ISSUE TITLE
issues with void elements in SSR

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#108]
Void elements shouldn't have a end tag. 

``` createNode("input").renderToString() ```

result: ```</input> ```
expected: ```<input> ```

**Comment by dfilatov** [comment]
Seems you don't even try to check because it returns `<input/>`.

**Comment by rickardjanson** [comment]
Why you say that? A void element doesn't have a end tag. And you clearly show to me here it's has an end tag.  Still an issue in your script.

Reference: 

From the W3C specs: http://www.w3.org/TR/html-markup/syntax.html#syntax-elements

http://www.456bereastreet.com/archive/201005/void_empty_elements_and_self-closing_start_tags_in_html/

**Comment by dfilatov** [comment]
There's no end tag in that case, just `<input/>`.

**Comment by rickardjanson** [comment]
Ah! I see it now. I was thinking about `/` as an end-tag. It isn't. Sorry!
