### ISSUE TITLE
not converting to param-case in SSR

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#109]
You are not converting to param-case in SSR, and that will cause wrong HTML markup.

``` createNode("div").attrs({ style: { zIndex: "1" } }).renderToString() ```

Result  ``` <div style="zIndex: 1;"></div> ```
Expected result  ``` <div style="z-index: 1;"></div> ```

**Comment by dfilatov** [comment]
@rickardjanson fixed, check
