### ISSUE TITLE
tag's are not rendered in lowercase in SSR

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#111]
HTML tag's are not rendered in lowercase in SSR

```  createNode("SPAN").children("Hello!").renderToString()  ```

Result: ```<SPAN>Hello!</SPAN>```

Expected result: ```<span>hello</span> ```

**Comment by dfilatov** [comment]
I don't think it's a problem. All browsers support both cases.
By the way, even React doesn't change case of tags.
