### ISSUE TITLE
performance tips - jsperf 

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#112]
Have a look at this jsperf: http://jsperf.com/prototypal-performance/215
You see there it's a huge performance difference. Any plans to do something with that?

Another one that still using the new keyword: http://jsperf.com/prototype-vs-instance-functions/15

**Comment by dfilatov** [comment]
Such synthetic tests aren't in touch with reality. Using of prototype isn't a bottleneck at all.
