### ISSUE TITLE
wrapped child node issues

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#116]
You suggested before that child nodes in an array that are text should be wrapped in a span tag as in REACT. First issue is that this is not W3C compliant, and the second issue are if you do this in CSS:
``` span { display: block }```  it would break the entire page.

As far as I understand REACT only does this because of their "react-id" thing.

**Comment by dfilatov** [comment]
I can't to get rid of wrapping because it will impossible to adopt existing DOM tree coming from server.

**Comment by rickardjanson** [comment]
@dfilatov Then you have to put up a warning sign that your code can break the entire webpage if you use CSS.
Anyhow. Why not check if it's a `typeof string` in the iteration loop

**Comment by rickardjanson** [comment]
@dfilatov  For adopting existing DOM tree coming from server, can you do something like.

1. Iterate through the nodes, and check if it's text string
2. If a textstring, grab it's children
3. Check for `childNodes.data` and iterate through
4. Replace current childNodes text conent with the `.data` value
etc.

**Comment by dfilatov** [comment]
Using of things like `span { display : block }` will broke your page anyway.

**Comment by dfilatov** [comment]
>For adopting existing DOM tree coming from server, can you do something like.
    Iterate through the nodes, and check if it's text string
    If a textstring, grab it's children
    Check for childNodes.data and iterate through
    Replace current childNodes text content with the .data value etc.

I've understood nothing from this mental continuum

**Comment by rickardjanson** [comment]
Here you find some server-side rendring:
https://github.com/Raynos/mercury/blob/master/dist/mercury.js

I will search for more ....

Can you try to find a solution that don't break the web page? I don't think people of your code would be so happy if the entire page break

**Comment by rickardjanson** [comment]
@dfilatov Another references that show you how to attach a virtual tree on a previous one:

https://github.com/trackira/trackira/blob/master/src/core/append.js

**Comment by rickardjanson** [comment]
@dfilatov Have a look at this code: https://github.com/DylanPiercey/tusk

As you see this guy are doing server side rendring as well, and he don't use any hidden spans etc. And he don't have the same issues as you have.

**Note!!** Study what he does to make the script fast with rendring - maybe you can adopt that?

**Comment by rickardjanson** [comment]
@dfilatov Why not use `document.createTextNode` instead of what you do now to avoid wrapping of text nodes? You don't need to add or use a prototype for that. 
After some research it seems like it's only you and REACT that does this dangerous things

**Comment by dfilatov** [comment]
Because when existing DOM tree is adopted I need to split single text DOM node to a couple of them. I don't like the idea to modify DOM at that moment.

**Comment by rickardjanson** [comment]
Did you study the Trackira solution I linked to yesterday about attaching the dom tree? See above. Is that a bad solution?

**Comment by dfilatov** [comment]
Seems it won't work for case I've written.

**Comment by rickardjanson** [comment]
I studied the code yesterday. First he using a append function in the Element node. However. Have a look at his mount in the tree. He have a append method there he using there. So when doing mount it seems he iterate through each child with the function I linked too and attach.

**Comment by dfilatov** [comment]
The function you linked doesn't resolve problem I've written.

**Comment by rickardjanson** [comment]
Ok. I just tried to help. Hopefully the code will be safe to use in the future. I'm offline
