### ISSUE TITLE
avoid use of innerHTML

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#117]
Try to avoid innerHTML if you can in the code. It has it's downsides.  So try to generate the DOM via DOM API. Much faster too !!

jsperf: http://jsperf.com/dom-vs-innerhtml/37
Stackoverflow: http://stackoverflow.com/questions/718091/alternative-for-innerhtml

**Comment by dfilatov** [comment]
I don't see places where I can avoid using of `innerHTML`.
