### ISSUE TITLE
SSR issues

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#118]
`Contenteditable` should be ignored during SSR.

Reference: https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Element/prototype/toString.js#L34-L37

And should you escape the value of a `textarea`? Because after what I understand, both select and textarea values shouldn't be stringified.

**Comment by dfilatov** [comment]
`select` and `textarea` values aren't stringified.

**Comment by dfilatov** [comment]
I can't understand from this source why `contenteditable` shouldn't be stringified. Could you provide any details?

**Comment by rickardjanson** [comment]
Ignored. In some cases this attribute ends up like `contentEditable=""` and shouldn't be set at all. There are other issues as well. See my issue ticket about this attribute and inherit

**Comment by rickardjanson** [comment]
And also sometimes value has to be set beforecontentEditable to work and vice versa. Also in table rows this attr can cause issues

**Comment by dfilatov** [comment]
"SSR issues", "In some cases", "There are other issues as well" — it's not a good description. Please attach example of non-working code!
