### ISSUE TITLE
prefer synchronous design

### ISSUE THREAD

**Issue by gaydenko** [dfilatov/vidom#12]
Hi!

Except for `update()` I have found asynchronous mode can be used on component unmounting. Probably, I have missed other places, but these two ones are here at least :)

I guess, rejecting an intention to keep all library operation synchronous is extremely strong and important decision. Current not-trivial SPA application can have very asynchronous operation mode, and adding additional asynchronous dimension on the presentation layer can significantly complicate overall design.

Possible complication concerns `update()` method especially: the method can be used extremely wide, and it is impossible to predict all those places where `update()` call can take place :)

I haven't found solid benchmark results proving the RAF is really unconditional winner. If at some use cases it is a winner, overcomplicating will (or can) neglect any vague profit.

So, I would suggest to eliminate any asynchronous modes from the library.

Of course, it may be the case I have missed some outstanding deep and wide researches proving RAF is a must have.

**Comment by dfilatov** [comment]
RAF isn't used for performance (especially for benchmarks), it's used to be integrated in the browser rendering lifecycle.
By the way, there're synchronous equivalents for the top-level `mountToDom/unmounFromDom` — `mountToDomSync/unmounFromDomSync` (they aren't documented now). 
Will it be suitable for you If I add synchronous equivalent for `update` as well?

**Comment by gaydenko** [comment]
> RAF isn't used for performance (especially for benchmarks), it's used to be integrated in the browser rendering lifecycle

Aha, I see, that is for smoother animation and saving trees (that is CPU consumption). I still haven't found solid information describing reality rather intention. It would be really interesting if you can provide a couple of hrefs.

Also, client-side apps are moving to CSS3 transitions and animations, and browsers are on the way to become more and more perfect here.

> ...there're synchronous equivalents for the top-level mountToDom/unmounFromDom — mountToDomSync/unmounFromDomSync (they aren't documented now). 

Yes, I have noticed `syncMode` in the code :)

> Will it be suitable for you If I add synchronous equivalent for update as well?

Absolutely! Thanks for intention!

Probably it would be handy to configure default `mount/update/unmount` mode(s) on higher level, say, on mounting. What do you think?

**Comment by dfilatov** [comment]
> It would be really interesting if you can provide a couple of hrefs.

Recently I've passed the course https://www.udacity.com/course/browser-rendering-optimization--ud860 and found it helpful.

> Probably it would be handy to configure default mount/update/unmount mode(s) on higher level, say, on mounting. What do you think?

I think it's better to follow common practice for such things. I would prefer to use nodejs-style, see https://nodejs.org/api/fs.html for instance.

**Comment by dfilatov** [comment]
I've implemented `updateSync` method in master branch.

**Comment by gaydenko** [comment]
> I've implemented updateSync method in master branch.

Great, thanks! As I see, you have also added a couple of very useful parameters to async call case (would the case be really needed) :+1:
