### ISSUE TITLE
can't mount normally anymore

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#123]
I can't mount this anymore

``` 
 var element = vidom.createNode("div").attrs( { style: {  display: "block", width: "10px" }  });
vidom.mountToDom(
document.getElementById("fooBar"),   element);
 ```
Nothing get attached if I look into the console.

**Comment by dfilatov** [comment]
Is `<div id="fooBar">` empty?

**Comment by rickardjanson** [comment]
It was not. Works if empty. Before it doesn't need to be empty. It could have nodes inside. Before it works like other VD implementations without this issue.

I also notice that CSS sometimes now become a object object.

**Comment by dfilatov** [comment]
> It was not. Works if empty. Before it doesn't need to be empty. It could have nodes inside. Before it works like other VD implementations without this issue.

Yes, after #120 it was changed.

> I also notice that CSS sometimes now become a object object.

Sometimes? I need case.

**Comment by rickardjanson** [comment]
If you see how DOM normally works with appendChild and insertBefore, you can insert even if not empty. Mount should work like that, or?

**Comment by dfilatov** [comment]
No, it shouldn't. I want to be able to adopt existing DOM tree.

**Comment by rickardjanson** [comment]
For CSS. Try to set a click event or css style inside a node you use as a reference in a component.

``` 
var InputComponent = fixzi.createComponent({
        onRender : function() {
            return vidom.createElement('div')
                .attrs({ className : 'input' })
                .children(
                    this.setDomRef( // add "control" reference to get corresponding DOM node further
                        'control',
                        vidom.createElement('input')
                            .attrs({
                                type : 'text',
								css: { width:"200px", height:"4200px"}, // not working!!
                                className : 'input__control',
								onClick: function() { alert("Hello, World!!") }, // not working!!
                                onFocus : this.onFocus.bind(this)
                            })));
        },

        onMount : function() {
            this.getDomRef('control').focus(); // use reference got in onRender()
        },

        onUnmount : function() {
        },

        onFocus : function() {
        }
    });
```

**Comment by dfilatov** [comment]
> css: { width:"200px", height:"4200px"}
there's no such attribute, you have to use `style` instead of `css`

**Comment by rickardjanson** [comment]
Ok. I tried that too. Didnt work

**Comment by rickardjanson** [comment]
And the event handler didnt work

**Comment by dfilatov** [comment]
`vidom.createElement`??? vidom has no such method. Mess.

**Comment by rickardjanson** [comment]
Ok. I experimenting with sub/functions to figure out why it wont work. I tried to create a sub/function that could write some console.log data and tried to avoid conflictt with native methods.

``` 
var InputComponent = vidom.createComponent({
        onRender : function() {
            return vidom.createNode('div')
                .attrs({ className : 'input' })
                .children(
                    this.setDomRef( // add "control" reference to get corresponding DOM node further
                        'control',
                        vidom.createNode('input')
                            .attrs({
                                type : 'text',
								style: { width:"200px", height:"4200px"}, // not working!!
                                className : 'input__control',
								onClick: function() { alert("Hello, World!!") }, // not working!!
                                onFocus : this.onFocus.bind(this)
                            })));
        },

        onMount : function() {
            this.getDomRef('control').focus(); // use reference got in onRender()
        },

        onUnmount : function() {
        },

        onFocus : function() {
        }
    });
```

**Comment by dfilatov** [comment]
This code works as expected:
  * styles are applied
  * input is focused

**Comment by rickardjanson** [comment]
And a hello wold pops up when you click? Or you can have double events? Not working here. Will check later

**Comment by dfilatov** [comment]
"Hello, World!!" popup shows as expected
