### ISSUE TITLE
[WRONG] vidom doesn't work in IE or Edge anymore :)

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#127]
Hi. From now on, vidom on IE and Edge are not working anymore. You have introduced use of ES6 classes.
This is not supported by that browser. 

You have to enable experimental JavaScript features in `about:flags` in `Edge`, there you can see `Enable experimental JavaScript features  `. Activate it, and classes being supported in Edge. 

I don't think people want to do this to use your script - if they know about it. If they don't know about it, well they will get suprised :)

Further. ES6 classes are in performance slower then prototype. And we know from before that constructor itself are slow.  

Summary from me is that I move away from your script for awhile. Simply because of this:

- CSS that can break your entire webpage. And there are no warning signs that this can happen.
- no IE support
- crazy mount feature that demand empty HTML tags and a lot more.

Bye for now !  My star are removed!!

**Comment by dfilatov** [comment]
Oh. Yet another bullshit.
I've moved to ES2015 only for development purposes. This code isn't supposed to be run in browsers directly. It should be transpiled before. After transpiling it becomes regular ES5 code which is supported by all browsers without any experimental flags. Have you ever heard about transpilers? If not, it's a good time for you to do this.
The best prove that everything still works is all tests are passed even in IE9.

By the way, as far as I understand you're able to run vidom, you use some build tool. Browserify, Webpack?

**Comment by rickardjanson** [comment]
Yes, I can run vidom. And I obviously also could run your ES2015. 
You ask if I have heard about transpilers? Well, if I don't know anything about Tracur, Babel etc., how did I get your code to run when you write I have to compile it? And the fact that some of your features now are only supported in Webkit browsers and FF ?
So stupid question to ask, isn't?

For ES5, yes. I got that code to run as well. And I didn't transpill it. How you ask? I will let you wonder. But you have options like rpm directly, gulp, webpack etc. And you have a lot of nice packages. Anyhow. Sindre Sorhus - the danish guy. You heard about him? 
He got a lot of nice tools you can use!  Here is his profile: https://github.com/sindresorhus?tab=repositories 

And you also find his tools on NPM.
So not so hard to get your code to work. Except why you are using phantomJS for server side testing, I don't know. Yes, you are using Zuul, but.. 
I prefer browserify, babelify, istanbul, uglify, testem ( yes, I know it's old) etc.

And you can't say this post is wrong. Because most of your code now work right out of the box without any transpillers in Webkit and FF. Except in IE and Edge. So without transpiller, ofc. I was right :)

But ofc. we shouldn't tak about knowledge here :) 

But once again. I'm out of it now!

**Comment by dfilatov** [comment]
Bye!
