### ISSUE TITLE
Provide some benchmarks that shows velocity profit against React

### ISSUE THREAD

**Issue by andre487** [dfilatov/vidom#145]
It will be helpful if there will be some benchmarks in the repo which measure velocity difference of several app implementations. Like [this one](http://vdom-benchmark.github.io/vdom-benchmark/) but more flexible. I mean that they should provide ability to replace implementations as black boxes. Something like Benchmark.js test cases which can be extended and replaced.

In this case developers can compare both libraries (or more of libraries) with different architecture implementations.

**Comment by dfilatov** [comment]
@Andre-487 Would you like to implement this? It will be great :-)

**Comment by Andre-487** [comment]
@dfilatov Yes. If I will find some time )

**Comment by dfilatov** [comment]
I has closed this issue. If you're still interested in such benchmark don't hesitate to do it and publish result :)
