### ISSUE TITLE
Contribute to React or join forces with React team

### ISSUE THREAD

**Issue by chicoxyzzy** [dfilatov/vidom#147]
Do you have any plans on contributing to React to share your experience and for big win of Open Source and JS community? If I understand correctly lightweight API and performance are goals of vidom. This is exactly what  React team and @sebmarkbage are want from React to be.

**Comment by zxqfox** [comment]
:+1: would be great to share one API and even use one module in many libraries.

**Comment by dfilatov** [comment]
I don't think it's possible because architectures of Vidom and React are absolutely different. What's more, I'm pretty sure that the concurrency model is better for Open Source.
