### ISSUE TITLE
Get DOM ref inside component

### ISSUE THREAD

**Issue by mrjjwright** [dfilatov/vidom#151]
I am sorry, but how do you get a dom ref inside a component?  I couldn't figure this out in the docs. 

Thanks and awesome lib!

**Comment by dfilatov** [comment]
Hi, John. To get a dom ref inside a component use `this.getDomRef(refName)`
https://github.com/dfilatov/vidom/wiki/Component-methods#getdomref

**Comment by mrjjwright** [comment]
But how to set a dom ref to the root node of the component?

**Comment by dfilatov** [comment]
Just as well for other nodes.

Plain js:
```js
onRender() {
    return this.setDomRef('bla', node('div'));
}
```
JSX:
```js
onRender() {
    return <div ref="bla"></div>
}
```

**Comment by mrjjwright** [comment]
Thanks!!
