### ISSUE TITLE
Use different client besides DOM

### ISSUE THREAD

**Issue by mrjjwright** [dfilatov/vidom#152]
I am looking to try another client for this lib besides the DOM (a Mac Cocoa binding).  I assume I would need to implement another set of client JS classes and then provide a set of patch operations in something like `_clientPatchOps2`.   What are your thoughts as to the feasibility of adding another client to this lib?

**Comment by dfilatov** [comment]
Currently there's no feasibility to implement custom nodes and custom patch operations.
