### ISSUE TITLE
Deprecate `isMounted`

### ISSUE THREAD

**Issue by himalayafan** [dfilatov/vidom#162]
https://github.com/facebook/react/issues/5465

**Comment by dfilatov** [comment]
I've read link you gave but can't understand what alternative is supposed.

**Comment by himalayafan** [comment]
Hey. It seems to me that they are going to use promises. I didn't find link for this, but I was reading last week in the React documentation an how-to-do this.

**Comment by himalayafan** [comment]
Ah sorry. Found some of the info now: https://github.com/facebook/react/pull/5587

**Comment by dfilatov** [comment]
It doesn't look like a solid solution. Workaround with using `cancellablePromise` works only for the first step. If you have chain of promises it won't work.
