### ISSUE TITLE
Rollup support

### ISSUE THREAD

**Issue by fmarsoni** [dfilatov/vidom#184]
Just need src folder in npm package and "jsnext:main": "src/vidom.js" in package.json

**Comment by dfilatov** [comment]
Could you explain for what?

**Comment by fmarsoni** [comment]
http://rollupjs.org
is an es6 module bundler. It allows better unused code exclusion and minification using es6 module syntax. 

Eg:

import { mountToDom, Component } from 'vidom';
class App extends Component {
	onRender() {
		return (<div></div>);
	}
}
mountToDom(document.getElementById('root'), <App/>);

results in a 10% size gain.
Things gets better including other es6 libraries supporting rollup.
Adding d3.js v 4.0 to the project and the lines:
import { min } from 'd3-array';
var minarray = min([1,2,3]);

results in a 20% gain in size (35 k with webpack, 28k with rollup)

**Comment by dfilatov** [comment]
Currently Vidom is built via rollup. Rollup gives a 20% size gain against browserify.
It seems keeping "src" folder inside npm package gives nothing more, just because bundled "lib/vidom.js" contains only needed parts of library.
