### ISSUE TITLE
dbmon bench?

### ISSUE THREAD

**Issue by leeoniya** [dfilatov/vidom#190]
Hey @dfilatov 

Do you have a dbmonster bench for vidom?

See: http://mathieuancelin.github.io/js-repaint-perfs/

mine's `domvm` :)

**Comment by dfilatov** [comment]
I've implemented it but haven't published yet.

**Comment by dfilatov** [comment]
PR to js-repaint-perfs https://github.com/mathieuancelin/js-repaint-perfs/pull/73
