### ISSUE TITLE
Issue with using Component in IE10 

### ISSUE THREAD

**Issue by tnajdek** [dfilatov/vidom#198]
All the test use createComponent directly and that ideed works fine in IE10 so the tests pass. However if the library is used as per the [tutorial](https://github.com/dfilatov/vidom/wiki/Tutorial) it will not work in IE10 where it errors with:

> Unable to get property 'renderToDom' of undefined or null reference

This can be observed on the official demo: http://dfilatov.github.io/vidom-todomvc/

A simple workaround is to use createComponent directly. Only IE10/IE9 are affected.

<img width="1019" alt="screen shot 2016-04-14 at 13 11 41" src="https://cloud.githubusercontent.com/assets/214628/14527519/8625021c-0242-11e6-901a-bce3bcfb5901.png">

**Comment by dfilatov** [comment]
Hi, @tnajdek! Thanks for the report.
The problem isn't with vidom itself, it's a consequence of usage babel stuff, see http://babeljs.io/docs/usage/caveats/ for details.
I've added `babel-plugin-transform-proto-to-assign` to the build pipeline for vidom-todomvc and now it's working as expected. Please, try it once more and give me feedback if something is going wrong.

**Comment by tnajdek** [comment]
ahh, that makes sense, thanks!
