### ISSUE TITLE
Repaint rate challenge in Edge browser error

### ISSUE THREAD

**Issue by stgolem** [dfilatov/vidom#240]
SCRIPT5007: Unable to get property 'childNodes' of undefined or null reference
vidom.min.js (1,30546)

**Comment by dfilatov** [comment]
It's definitely a bug.

**Comment by dfilatov** [comment]
@stgolem Thank you for the report!

**Comment by dfilatov** [comment]
Will be fixed in  #241

**Comment by dfilatov** [comment]
fixed
