### ISSUE TITLE
You are missing both SVG and Math namespace.

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#26]
You are missing both SVG and Math namespace.
Reference: Reference: https://github.com/joelrich/citojs/blob/master/dist/cito.js#L242-L247

**Comment by rickardjanson** [comment]
@dfilatov  There is also an quick fix to this issue. See my suggestion for solution here: https://github.com/dfilatov/vidom/issues/27

After you got your parent, you can check like this:

```


// use svg
    if (this._tag === "svg") {
        this._ns =  "http://www.w3.org/2000/svg";
    }
    if (this._tag === "math") {
               this._ns = "http://www.w3.org/1998/Math/MathML";
    }

// And then the magiv happen with inheritate from parent
    if (parent) {
        this._ns = parent._ns;
    }


```

**Comment by dfilatov** [comment]
You have to specify corresponding namespace for root svg tag. Inner nodes inherit it.
