### ISSUE TITLE
namespace need to be inherited from it's parent

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#27]
namespace need to be inherited from it's parent, if parent exist. Meaning you need to have a parent variable that get set when you create an element - 'renderToDOM'.  
Same 'parent' need to be used again when you do patching.

Reference: https://github.com/joelrich/citojs/blob/master/dist/cito.js#L242-L247

**Comment by rickardjanson** [comment]
@dfilatov There is an easy fix to this issue, and you can solve it stright away if you change your code in this lines, to my suggestion:  https://github.com/dfilatov/vidom/blob/master/lib/nodes/TagNode.js#L50-L63

Solve issue if you do:

```
// adding parent as the second argument, you got your parent and can inherit from it
  renderToDom : function(ctx, parent) {
        var domNode = this._ns?
                doc.createElementNS(this._ns, this._tag) :
                doc.createElement(this._tag),
            children = this._children,
            attrs = this._attrs,
            name, value;

        if(children) {
            var i = 0,
                len = children.length;

            while(i < len) {
                domNode.appendChild(children[i++].renderToDom(ctx, this));
            }


```

**Comment by dfilatov** [comment]
It's no so easy to fix that because there's patch operation which should consider parent namespace.

**Comment by rickardjanson** [comment]
I see. So when do you plan to fix this?

**Comment by dfilatov** [comment]
as soon as possible

**Comment by dfilatov** [comment]
fixed, check

**Comment by rickardjanson** [comment]
verified!
