### ISSUE TITLE
Low IE performance

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#28]
Bad performance all over in IE. Solution would be to create the element first, append it to parent container, and then do the render.

Reference:  https://github.com/joelrich/citojs/blob/master/dist/cito.js#L258-L266
                   https://github.com/joelrich/citojs/blob/master/dist/cito.js#L286-L288

**Comment by dfilatov** [comment]
Could you provide some benchmark?

**Comment by rickardjanson** [comment]
I can do better then that.  Read this:

Reference: https://github.com/localvoid/vdom-benchmark/issues/15#issuecomment-71689398
