### ISSUE TITLE
Analog of dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by Urkass** [dfilatov/vidom#314]
Hello, React has such ComponentNode attribute as `dangerouslySetInnerHTML` for inserting html "as it is".
I haven't found any analog of this in vidom. What is the proper way to insert such html? Or are there any plans for adding such possibility?

**Comment by dfilatov** [comment]
Hi, @Urkass 
https://github.com/dfilatov/vidom/wiki/TagNode-API#sethtml

**Comment by Urkass** [comment]
Thx, haven't noticed
