### ISSUE TITLE
IE 11, [object Object] in style attribute

### ISSUE THREAD

**Issue by Urkass** [dfilatov/vidom#316]
Es6 Map [isn't fully](http://kangax.github.io/compat-table/es6/#test-Map) supported in IE 11.
[This](https://github.com/dfilatov/vidom/blob/master/src/utils/SimpleMap.js#L3) place of choosing the usage of es6 Map or SimpleMap leads to mistake:
[Here](https://github.com/dfilatov/vidom/blob/master/src/client/domAttrs.js#L163) we try to fullfill es6-map throught the constructor, but map constructor arguments are not supported in ie, thats why it stays empty.
And then trying to get `'style'` property leads to nothing. [When](https://github.com/dfilatov/vidom/blob/master/src/nodes/TagNode.js#L279) `domAttrs('style').toString` is called - native object's `toString` method is used, instead of `stylePropToString`, so it leads to `'[object Object]'`.
I think it can be cured with some ponyfill like [this](https://www.npmjs.com/package/es6-map), but it's up to you. What do you think?

**Comment by dfilatov** [comment]
I think we can better check for support of `Map` and fallback to the current polyfill for IE11. I'm going to investigate to this today.

**Comment by dfilatov** [comment]
@Urkass Thank you for the report and especially for your investigation to the source of problem, you've saved me a bit of time.
