### ISSUE TITLE
className forced to be class and vice versa

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#32]
In default DOM standards, there are differences between attributes and properties. Some attributes can be set as properties and the other way around.

You are only focusing on setting `className`, but what about `class`? `class` are the only working attribute in `svg`.

It should be up to end-devs to decide whatever to set an attribute or a property as in a normal DOM way. But I agree you should keep you attribute whitelist, and also create a whitelist for properties.

Therefor I suggested a separated `property object` as I see that citoJS now also want to support that.

Reference: https://github.com/joelrich/citojs/issues/8#issuecomment-98472610

**Comment by dfilatov** [comment]
Have you tried to do it? It seems that both variants should work.

**Comment by dfilatov** [comment]
should work now, check

**Comment by rickardjanson** [comment]
@dfilatov  verified!!!
