### ISSUE TITLE
no server side rendring

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#37]
Seems like there are no server side rendring.

**Comment by rickardjanson** [comment]
@dfilatov What is your plans for server side rendring?

**Comment by dfilatov** [comment]
My plan is to implement SSR.

**Comment by dfilatov** [comment]
Rendering to html string is implemented via 51da94808374e38daf62d7e680a8e9e8f6442b18.
The next step is to implement ability to adopt existing DOM tree to a virtual one, see #103.
