### ISSUE TITLE
Why are you passing DOM event handlers via attrs ?

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#40]
Why are you passing DOM event handlers via attrs ?

As in the default DOM specs, we have `onClick`, `onMouce` etc. This is not supported by you, or I'm wrong?
So overriding this with DOM event handlers on attrs are going against the DOM specs. Considered having it's own Event variable?

Maybe this can give you some ideas: https://github.com/jhudson8/react-events

**Comment by dfilatov** [comment]
The event handlers are separated from usual attributes inside engine.

**Comment by rickardjanson** [comment]
Ah I see. But how are I'm going to get a onClick property to work as after the DOM specs?

**Comment by dfilatov** [comment]
Sorry, I can't understand your question. Could you give more details?

**Comment by rickardjanson** [comment]
Default HTML standard would be:

``` <button onclick="myFunction()">Click me</button> ```

and `onClick` is an property. So a natual solution would be like this:

``` { props: { onclick: myFunction() } }```

This is normal defacto DOM and HTML standards.

What you are doing is to overwrite the defaults. Even REACT doesn't do that. You can set `onClick` as an property. And they have separated event system.

**Comment by dfilatov** [comment]
Actually REACT does: https://facebook.github.io/react/docs/events.html

**Comment by rickardjanson** [comment]
I know what they are doing, but they are making an equalent to default DOM standards, and not overwriting. You can get an idea from here too:  https://github.com/dekujs/deku/blob/master/lib/events.js

They take a normal event and add `on + event` and store it in a internal register. This to be equal to the DOM properties. They are not overwriting anything.

Code snippet directly from REACT source code so you see it:

```
function isEventSupported(eventNameSuffix, capture) {
  if (!ExecutionEnvironment.canUseDOM ||
      capture && !('addEventListener' in document)) {
    return false;
  }

  var eventName = 'on' + eventNameSuffix;
  var isSupported = eventName in document;

  if (!isSupported) {
    var element = document.createElement('div');
    element.setAttribute(eventName, 'return;');
    isSupported = typeof element[eventName] === 'function';
  }

  if (!isSupported && useHasFeature && eventNameSuffix === 'wheel') {
    // This is the only way to test support for the `wheel` event in IE9+.
    isSupported = document.implementation.hasFeature('Events.wheel', '3.0');
  }

  return isSupported;
}
```

**Comment by dfilatov** [comment]
I have the similar registry: https://github.com/dfilatov/vidom/blob/master/lib/client/events/attrsToEvents.js

**Comment by rickardjanson** [comment]
I see. Just let me think for awhile. Maybe not so stupid your ideas, but I see issues here you don't see :) And I have to think how to gain better performance on this one, because you have slow downs in your code here. I will start to analyze now.

**Comment by rickardjanson** [comment]
Ok. I'm done thinking. After all this is my expert field :)

Children can be both a `tag` and a text node. 
In clear speaking nodeType 1 an nodeType 3. 

A nodeType 3 can't have anything attached to it, not even a handler. So when you do a unmount, you do a lot of checking you don't need. 

What if the node is a nodeType 3?

So we need a workaround.  Set a `flag` for each node. Example:
```
flag.Tag = 1
flag.Text = 2
flag.Component = 3
```
Then you can have some fun, and don't need a  `typeof` that will slow things down.

So in your `unmount` section in the `TagNode`, you change `unmount` to

```
 while(i < len) {
var child =   children[i++];
if ( child.flag === 1) 
if ( child.flag === 2) 
if ( child.flag === 3) 
           }
```
Then you can do specific things for each node. You can also use this flagging else where in your code.

I come up with this, because on ```line 122```, you are unmounting a event handler. But what if a child node got a listener? You should attach the handler on the root level etc document, and bubble up and down. And have option for the child node if TagNode to remove the handler on that node as well to `avoid memory leaks`.

However. This can be an killer as well.

Benefits here is that you can do special things for each node that is not supported for another node, and get faster iteration. Another benefits are you can avoid memory leaks.

When it now comes to events on the attributes as you do, I see what you doing and I like it. But this are also properties, so then you need or at least should create a property object as mentioned before.
