### ISSUE TITLE
fixes for screwed up virtual Text

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#42]
hmm... What to say. I think you did a couple of mistakes....  I'm comparing with other VD libraries now, and try to help you out.

Your virtual text are fucked up. It would need a change. To the better :)

Change this https://github.com/dfilatov/vidom/blob/master/lib/nodes/TextNode.js#L23-L25
to this:

```
renderToDom : function() {
var domNode = this;
if (!domNode ) {
        domNode  =doc.createTextNode(this._text);
}
return this.domNode;
    },
```

Then again. In your Text node you have a noop function for unmount().  I don't like that, so try to change that to this:

```
var domNode = this;
if (domNode .parentNode) {
        domNode .parentNode.removeChild(domNode );
    }
```

Then we fixed unmount() for your text. I'm still investigating...

**Comment by dfilatov** [comment]
I can't understand why I should change `renderToDom` to your version. `renderToDom` is called once for each node.
`unmount` isn't for dealing with DOM operations.

**Comment by rickardjanson** [comment]
`renderToDom` just creating a `this.domNode`. So you can remove parentNodes. But I will come back to this soon with a TagNode suggestion

**Comment by dfilatov** [comment]
`So you can remove parentNodes`
What for?

**Comment by rickardjanson** [comment]
A lot of reasons, mostly memory. But if you are 100% sure you get rid of all child nodes if you remove it's parent, it's not needed. But in IE - some versions - that will not happen. The nodes will be without a reference and just exist in the blue.

**Comment by rickardjanson** [comment]
For you TagNode. See this line: https://github.com/dfilatov/vidom/blob/master/lib/nodes/TagNode.js#L110-L123

@dfilatov In case you doubt what I'm doing, check out citoJS as one example.

Anyway. This can also be optimized for better performance. So I suggest this solution here:
```
// Performance fix
  var children = this._children;

        if(children) {
             // Quick solution if only one child node
          if(children.length === 1) {
              children[0].unmount();
          } else {
            var i = 0,
                len = children.length;

            while(i < len) {
                children[i++].unmount();
            }
        }
}
// Check again for the damn parentNode
var parentNode = node.parentNode;
if (parentNode) {
parentNode.removeChild(node);
}
```
Referance: https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Element/prototype/detach.js

**Comment by rickardjanson** [comment]
@dfilatov This for unmount. You will still get event issues after this? Then a re-write. I¨m offline now.

**Comment by rickardjanson** [comment]
@dfilatov Stupid me. I forgot one reference for you: https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Text.js
