### ISSUE TITLE
Can't run benchmark with the new changes

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#43]
Hi. I just saw your new changes, and wanted to benchmark it. But I ran into a couple of issues.

When I run the benchmark with current setup, `removeChild()` second argument are `null`

Seems like for text nodes that the `_domNode' are not set? In console.log too it show me a null.

Maybe you have to adjust the benchmark setup?

**Comment by rickardjanson** [comment]
After investigation I can say it only return correct object as the second argument. But if you do a console.log on the second argument, you will see tht domNode = null. It's not created.

removeChild will then throw TypeError: `Argument 1 of Node.removeChild is not an object.`

**Comment by dfilatov** [comment]
new changes are in progress, let's not use them until I have еnded them up.
