### ISSUE TITLE
boolean attributes missing

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#47]
Hi. I can't see how you are handling boolean attributes!

**Comment by dfilatov** [comment]
Please try at least before create issue.
```js
vidom.mountToDom(
    rootDomNode,
    vidom.createNode('button').attrs({ disabled : true }).children('work'));
```
It works.

**Comment by rickardjanson** [comment]
Agree. Disabled are also a property. So how are I'm going to set it as a property? You are only showing me setting it as an attribute.   

Take a look here: https://github.com/joelrich/citojs/blob/master/dist/cito.js#L739-L750

**Comment by dfilatov** [comment]
>  So how are I'm going to set it as a property

What's a purpose? What do you want to get? It works now and as user you get correct result.

**Comment by rickardjanson** [comment]
I'm not the developer here. I guess this would be a good read for you: https://github.com/facebook/react/blob/847357e42e5267b04dd6e297219eaa125ab2f9f4/src/browser/ui/dom/HTMLDOMPropertyConfig.js
