### ISSUE TITLE
select and select multiple

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#48]
select and select multiple seems to have issues. Values not set correctly or loaded corectly during pageload. There are some IE issues here too that you are not aware of.

Seems also to be an issue with select in a select group with multiple children.

Are this going to be fixed?  And selectedIndex?

**Comment by dfilatov** [comment]
Please attach code you use and the result you got. Otherwise it's hard to understand, especially "There are some IE issues here too that you are not aware of."

**Comment by rickardjanson** [comment]
Basic knowledge my friend :) Ie are trouble some. You need references? Okey, here we go for a few:

*Input in IE:*
https://github.com/Matt-Esch/virtual-dom/issues/287

Others:  https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/index.js#L43-L48

A good start is to read the jQuery source. There you find all IE bugs, **selectedIndex** issue for IE, and a bunch more.

**Comment by dfilatov** [comment]
closed in favour of #65
