### ISSUE TITLE
I can't set properties!

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#49]
Sometimes I wanted to set some properties, but I can't! Will this be fixed?

Example `select multiple` needs to be an property, but others as well I can do

```
node.id = // id
node.checked = // checked
node.selectedIndex = // class
node.className = // className
node.selected = // selected
```
and many more.

For example for selected, you can only set it as an attribute, but it is in fact a property too.

**Comment by dfilatov** [comment]
Have you tried?

```js
vidom.mountToDom(
    rootDomNode,
    vidom.createNode('select').attrs({ multiple : true }).children([
        vidom.createNode('option').children('option1'),
        vidom.createNode('option').attrs({ selected : true }).children('option2'),
        vidom.createNode('option').children('option3')
    ]));
```
![screen shot 2015-08-01 at 13 59 01](https://cloud.githubusercontent.com/assets/67957/9021636/963414d4-3855-11e5-9e8d-1968b866d2c8.png)

**Comment by rickardjanson** [comment]
You show there only one selected. What about two? I faces issues in webkit and IE. As you know IE have a lot of issues with this. Also Android 4.1 - 4.3 have trouble with selecedindex. IE can return 0 or null sometimes etc.

**Comment by dfilatov** [comment]
Issue with multiple select was fixed. Check.
