### ISSUE TITLE
can't render into shadow dom

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#52]
Seems there are no shadom DOM and shadow root support?

**Comment by dfilatov** [comment]
I'm not going to support shadow DOM.

**Comment by rickardjanson** [comment]
Ok. Just to let you know there is a bunch of issues if you don't support at least the basics.

A qlue could be who is the owner in your script? Ownerdocument? Search through REACT source and you see a lot of references to owner. What if the root node is a show? Issue!

Up to you. Here are some references:

https://github.com/facebook/react/issues/3763
https://github.com/facebook/react/pull/859
https://github.com/facebook/react/pull/2617
https://github.com/facebook/react/pull/4150
https://github.com/facebook/react/pull/1167

**Comment by dfilatov** [comment]
According to http://caniuse.com/#feat=shadowdom most of the browsers don't support it
