### ISSUE TITLE
merge iteration loops

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#53]
If you have less iteration loops, better performance. For your update attributes, you are iteration through old and new attributes - 2x loops.

Look here: https://github.com/AFASSoftware/maquette/blob/master/src/maquette.js#L158

Only one iteration loop.

**Comment by dfilatov** [comment]
That implementation has unsuitable assumption, see https://github.com/AFASSoftware/maquette/blob/master/src/maquette.js#L164

**Comment by rickardjanson** [comment]
I see. Bad reference. So here is a better reference covering the same issues: https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/apply-properties.js

**Comment by dfilatov** [comment]
It has the same problem https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/apply-properties.js#L10
