### ISSUE TITLE
transitions and animation 

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#54]
lacking support for transitions and animation. Are this going to be supported?

**Comment by dfilatov** [comment]
What exactly do you mean by lacking support???

**Comment by rickardjanson** [comment]
lacking = missing = not implemented into your code. You can't claim that - yes you are supporting css - and that is it. Transistions need event handlers attached to them etc. And this transitions events have different names in different browsers.

So how are you going to do animation? Like velocity etc?

**Comment by dfilatov** [comment]
You are able to use any animation library you like. vidom is not for dealing with animation, it is out of scope.

**Comment by rickardjanson** [comment]
Ah okey. Because after what I know, CSS supporting declarativ animation such as transitions, etc. So if this is out of scope, you can\t claim you are supporting css either. Because this is a huge part of css.

**Comment by dfilatov** [comment]
Could provide any examples how other virtual libraries support animations and transitions?

**Comment by rickardjanson** [comment]
https://github.com/ractivejs/ractive/tree/dev/src/virtualdom/items/Element/Transition

**Comment by rickardjanson** [comment]
https://github.com/paldepind/snabbdom/blob/master/modules/hero.js

**Comment by rickardjanson** [comment]
Good to know you wont fix this. But then again if people ask you if you support CSS, you can't claim that you do that. Or you need to put up info that you are only supporting 50% of CSS standards today.
