### ISSUE TITLE
xmlns not supported

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#55]
xmlns are not supported.

**Comment by dfilatov** [comment]
Please, attach an example of non-working code.

**Comment by rickardjanson** [comment]
Sure. Here you go:

```
var mathURI = "http://www.w3.org/1998/Math/MathML";
var  element = createNode("math").attrs( { xmlns: mathURI } ).renderToDom();
```
Expected: `element.namespaceURI equal to mathURI`

I know you have to set namespace first, but still `xmlns` are not working.

Another thing, you should set `auto-detection` of namespace to prevent stupidity or maybe not?

Example check if `this_tag` are equal to either svg or math and set namespace automaticly if not already set.

**Comment by dfilatov** [comment]
You have to set xmlns through `ns` method, not through `attrs`.
