### ISSUE TITLE
svg tag issues

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#56]
if you create a svg element with a circle as it child, it will not inherit from it's parent and get same namespace. So it will not be visible.

Rendring svg element inside a div or span tag, and it will not be visible.

There are no SVG namespace either.

**Comment by dfilatov** [comment]
Fixed, check. But keep in mind you have to specify corresponding namespace for root svg tag.

**Comment by rickardjanson** [comment]
verified!
