### ISSUE TITLE
not added support for `rdfa attributes` 

### ISSUE THREAD

**Issue by ghost** [dfilatov/vidom#58]
not added support for `rdfa attributes` such as `resource`, `about`, `property`? http://www.w3.org/TR/rdfa-core/#h-s_syntax

**Comment by dfilatov** [comment]
Attach an example which demonstrates a problem

**Comment by rickardjanson** [comment]
Very hard to do that, because as menioned many times. You are not supporting namespace attributes in the way it should. So I can't give an example. It will not work!!

Reference: http://www.w3.org/TR/rdfa-syntax/
