### ISSUE TITLE
Missing support for document.activeElement

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#61]
Missing support for `document.activeElement`. Mostly all libraries supports this. Your's don't.
I'm not a teacher or anything, so you need to add this. You find out yourself.

**Comment by dfilatov** [comment]
Please, attach example which shows a problem.

**Comment by rickardjanson** [comment]
Ok. First. This is basic knowledge. Second. I can give you an example because I can't update a DOM tree!

**Comment by rickardjanson** [comment]
See this issue: https://github.com/dfilatov/vidom/issues/64

**Comment by dfilatov** [comment]
you can update dom tree, see the answer in the related task
