### ISSUE TITLE
Aria support? 

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#62]
See angularjs. Aria are you going to support?

**Comment by dfilatov** [comment]
You are able to use aria attributes.

Ps. I'm not going to support everyl feature you have found in a huge number of other libraries.

**Comment by rickardjanson** [comment]
I understand that. But ARIA are a well common attribute that all supported. Even AngularJS. It helps for quickly updates HTML without overhead etc. 

And if you create a virtual DOM, it should be natural it's a replicate / copy of the real DOM. DOM after the specs - DOM Leel 0 - DOM Living. But after all most of this are not supported in your script.
