### ISSUE TITLE
Doctype, comment and fragment 

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#63]
How are you going to support doctype,  comments and fragment?

**Comment by rickardjanson** [comment]
Just closing without answers? Ok. I can give references to this too, and point out it's supported by virtual dom implementations.

**Comment by dfilatov** [comment]
I'm not going to support these things until you give some valuable real examples of their usages.

**Comment by rickardjanson** [comment]
*comments* - normal in HTML. Say someone want to create a template with your VD. Valid HTML markup does contain comments. Or say someone working on a project and does HTML markup with your VD and want to send it to a person to verify it. It's normal to put comments in the markup so the other person knows what's going on.

*fragments* can be usefull if you have multiple children etc, and want to avoid touching the DOM too much.

*docType*. Same as for comments. If you need to create a full HTML markup with docType on the top, you can't. This mostly belong to the server-side rendring and not front end / client-side.
If not possible to create a docType when rendring a complete HTML page, you get issues in Internet Explorer. IE will not work without a valid docType.
