### ISSUE TITLE
can't update a DOM tree

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#64]
How are I'm going to update a DOM tree????  I'm not talking about hooks or "onUpdate".

Illutrated.

- you create a virtual element and mount it. And later on want to update that element. How can I do that?

In all other virtual DOM implementation, this is done so easy as:

  update(node1, node2)

References:  https://github.com/trackira/trackira#update
                     https://github.com/joelrich/citojs/blob/master/dist/cito.js#L1250-L1256

So for the activeElement, I can do anything. Because you can't update the nodes. So there is an issue.

**Comment by dfilatov** [comment]
to update dom just mount another virtual tree to the same dom node
