### ISSUE TITLE
undefined not ignored - confirmed

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#66]
In fact, there is no point to try to set `undefined` on `attributes` and `properties`. Still you are doing just that. I don't know why?

```
 var node = createNode("input").attrs({class: undefined}).renderToDom();
```
Expected output here should be a falsy value.

Also for `value` as you set as an property (*should have been a attribute*) does the same

```
 var node = createNode("input").attrs({value: undefined}).renderToDom();
```
Expected a falsy value here too.

And if you do this too:

```
"value" in node
```

it will return a `true` value !!!  How can that be?

**Comment by dfilatov** [comment]
fixed, check

**Comment by rickardjanson** [comment]
Verified!!
