### ISSUE TITLE
cant cast empty value as empty string

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#67]
Hi. You cant cast empty value as empty string.

Try to patch this:

```
   var node1  = createNode("input").attrs({ value: "hello" });
     var node2 = createNode("input").attrs({ value: null });
```
You will get some nasty errors :)

**Comment by dfilatov** [comment]
I've tried to do this and haven't got any errors and see expected result. Which nasty errors did you get?

**Comment by rickardjanson** [comment]
I don't get any nasty errors because you fixed the undefined issue. So solved.
