### ISSUE TITLE
children issue !!!

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#75]
Hi. Here is another nasty issue :)

Try to render this, what is your output?

```
 var dfilatov = createNode("ul").children([
		  createNode("li").key(1).children("t0"), 
		  createNode("li").children(["t", "1"]), 
		  ]).renderToDom()
```
Result: ``` TypeError: children[(i++)].renderToDom is not a function ```
Expected result: ```"<ul><li>t0</li><li>t1</li></ul>"```

**Comment by rickardjanson** [comment]
@dfilatov It's very important to think about performance if you solve this issue.

**Comment by dfilatov** [comment]
I don't think it's a good idea to allow such syntax: `,children(["t", "1"])`.
It makes me to check all items in array and can brings perfomance problems.

**Comment by rickardjanson** [comment]
If you choose not to allow it, you need to find a way to stop this error message.

**Comment by dfilatov** [comment]
How do `range` helps me with this issue?

**Comment by rickardjanson** [comment]
`range` help improve performance if you have many children. Just check how REACT uses it for children

**Comment by dfilatov** [comment]
How is it related with this issue???

**Comment by rickardjanson** [comment]
Just say you have an array as illustrated here. And there are many children in this array, maybe 10. Then this will improve it.
Other way around is also to check the length of the array, and skip iteration if possible.

Example if the length of the array = 1, you can simply do this: `array[0]` and no iteration at all.

**Comment by dfilatov** [comment]
It doesn't help to process `.children(["t", "1"])` at all.

**Comment by rickardjanson** [comment]
How come? In the processChildren method you have, you are checking if array

`isArray(children)`

```
// Sorter, filter an create new array
var newArray = []

// iterate through the old array

// is it text , number etc? 
newArray.push(children[i]);

// at the end 

return newArray;
```

**Comment by dfilatov** [comment]
There's performance issue to recreate array children.

**Comment by rickardjanson** [comment]
I agree in that, and the performance issue can be removed if you pre-set the length of a new Array first. Like this `new Array(12)`

**Comment by rickardjanson** [comment]
@dfilatov If you are worried about performance, you should start to iterate from `-1` and not `0` in all your loops too. 

Example:

```
   var arr = collection || [],
                index = -1,
                length = arr.length;
            while ( ++index < length ) {}
```

**Comment by dfilatov** [comment]
> you should start to iterate from -1 and not 0 
proves?

**Comment by rickardjanson** [comment]
Well. You know that loadash are build for great performance?? And the fastest utility belt library?

So in their `each()` method this is used. See this jsperf: http://jsperf.com/jquery-foreach-vs-for/8

Code snippet from the source:
```
 /**
     * A specialized version of `_.forEach` for arrays without support for callback
     * shorthands and `this` binding.
     *
     * @private
     * @param {Array} array The array to iterate over.
     * @param {Function} iteratee The function invoked per iteration.
     * @returns {Array} Returns `array`.
     */
    function arrayEach(array, iteratee) {
      var index = -1,
          length = array.length;

      while (++index < length) {
        if (iteratee(array[index], index, array) === false) {
          break;
        }
      }
      return array;
    }

```

**Comment by dfilatov** [comment]
lodash do that not for performance. It's related to performance at all.

**Comment by rickardjanson** [comment]
Anyhow. Here you see them all.  https://jsperf.com/loops/33

**Comment by dfilatov** [comment]
On my computer test where index is started from 0 is faster than -1. But I'm sure this difference has no any real sense.

**Comment by rickardjanson** [comment]
I tend to agree.
