### ISSUE TITLE
Can't create empty text nodes

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#77]
After all "" are text, but empty text. And this is not working. 

Try this:

```
 var empty = createNode("div").children("").renderToDom();
```
Then check the `childNodes.length`

Result: 0
Expexted 1

**Comment by dfilatov** [comment]
Can't reproduce. I've got `1` for `childNodes.length`. Please, check.

**Comment by rickardjanson** [comment]
I probably checked this after you checked the null issue with children. It's fixed now. So you can close :)
