### ISSUE TITLE
Improve patching algorithm

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#80]
You can improve the patching algoritm if you know that ChildrenA don't exist, and ChildrenB exist. OR childrenB exist and ChildrenA don't exist. This will also save memory and give better performance.

Reference: https://github.com/localvoid/kivi/blob/master/src/vdom.js#L736-L807

**Comment by dfilatov** [comment]
These cases are already processed:
https://github.com/dfilatov/vidom/blob/master/lib/nodes/TagNode.js#L140
https://github.com/dfilatov/vidom/blob/master/lib/nodes/TagNode.js#L145

**Comment by rickardjanson** [comment]
@dfilatov They are not! Look one more time. You are processing if either A or B have no children. I'm talking about if either A or B have only 1 child node.

**Comment by dfilatov** [comment]
It's the same.
If A doesn't have children and B has 1 child: https://github.com/dfilatov/vidom/blob/master/lib/nodes/TagNode.js#L145
and vice versa:  https://github.com/dfilatov/vidom/blob/master/lib/nodes/TagNode.js#L140
