### ISSUE TITLE
Any plans to support value types?

### ISSUE THREAD

**Issue by ghost** [dfilatov/vidom#84]
Reference: https://github.com/facebook/react/issues/3226

**Comment by rickardjanson** [comment]
@dfilatov Are value types going to be supported? I think that can improve the performance, for after what I understand you don't need to have a normal diffing process. Only compare values in some cases.

**Comment by rickardjanson** [comment]
@dfilatov Are value types going to be supported?

**Comment by rickardjanson** [comment]
@dfilatov No plans for this?

**Comment by dfilatov** [comment]
At that time it's not essential. I need to implement more priority things.
