### ISSUE TITLE
use plain objects?

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#86]
Reference: https://github.com/facebook/react/pull/3942/files

**Comment by dfilatov** [comment]
Please, describe you proposal. Link to changed files in another repo absolutely isn't enough.
Please, write sensible desription for your issues. I have no so much time to understand every time what you really want. My friend, it's a basis for mutual understanding.

**Comment by voischev** [comment]
@dfilatov +1

**Comment by rickardjanson** [comment]
My idea was to reduce the usage of `this` and `new` keywords - performance killer. And use plain objects where it can be done. Example for the text node? Convert it to a plain object.

And for the component part as well, plain object.

**Comment by dfilatov** [comment]
Using of `this` is highly optimized in modern browsers and avoiding it can't bring any valuable boost.
