### ISSUE TITLE
ContentEditable edge case - inherit

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#87]
ContentEditable is an edge case. The browser use `inherit` by default on all nodes, but does not allow setting it to `""`. 

Reference https://github.com/Matt-Esch/virtual-dom/issues/176

**Comment by dfilatov** [comment]
Attach non-working case or I have to close this issue.

**Comment by rickardjanson** [comment]
I thought you know how to read? See reference. Or bugs for various browsers. But up to you if you want to fix this or not. But honestly I don't think it's problem in your script because in all cases it's not a good idea to use CSS coz the whole page will break. And this issue are caused by `inherit|
