### ISSUE TITLE
`this.getDomRef` same as findDOMNode ?

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#88]
Hi. Just wonder if your method `this.getDomRef` is equal to `REACT findDOMNode` ?
It doesn't look like it. Couldn't it be a idea to have a `vidom.findDOMNode()` method?

Reference: https://facebook.github.io/react/docs/working-with-the-browser.html#refs-and-finddomnode

**Comment by dfilatov** [comment]
`Component#getDomRef` already returns dom node, so there's no need to have `findDOMNode`.
