### ISSUE TITLE
plan to use the new fragment concept?

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#91]
Just wonder....

**Comment by dfilatov** [comment]
I haven't seen how fragments are speedings things up. Could you explain?

**Comment by rickardjanson** [comment]
Hi. First off you need to include support for value types as coming in REACT 0.14. See my other issue regarding this.  And you know how value types are working? For value types you can find this article interesting: http://smallcultfollowing.com/babysteps/blog/2014/04/01/value-types-in-javascript/
After reading that one, you should  know that swapping value content are faster then iterate through with a loop. And easy to optimize.
Then it comes to fragments. This is not document fragments, but rather a concept where you have one container object - {} and add remove fragments to it.  Checking if the fragment exist already from previous call / iteration, and don't re-build it if it exist. Only grab that fragment and do magic with it.
That means. Say we want to update a list. Then we got a subtree, and each subtree is a fragment. it will simply add a fragment to the bottom and update all other sub trees to reflect their values. Same principe as value types.
I don't know 100% how this is working, but this is what I understand so far.

**Comment by rickardjanson** [comment]
So the trick here should be to avoid to generate a vdom on each render. Simply return only the values and a template id, and then use that template id to build the fragments.  virtual fragments.

**Comment by rickardjanson** [comment]
or maybe you could develop something new. Let us say you create the vdom on the first render. Cache it somewhere, and have a boolean flag on the parts you know are going to change. 0 / 1.
So when you patch etc, grab the already rendered vdom and check the flags. And then upate it's content after the boolean flags. In a `value type` way of doing things.

**Comment by rickardjanson** [comment]
@dfilatov You went quiet the last day, so I just wonder. Did you understand how this works, and are you going to integrate this or something similar? What is your next plan for vidom?

**Comment by dfilatov** [comment]
I'm planning to do some minor perfomance improvements and move to improving of other features of the library.

**Comment by rickardjanson** [comment]
So when are this changes done?

Btw. Have you seen this? https://github.com/astoilkov/jsblocks/blob/master/src/query/VirtualElement.js

Same concept as yours?
