### ISSUE TITLE
issues with textarea, buttons, checkbox and radio

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#92]
A textarea's `value` should be set as an HTML attribue not a property. Else it will not accept numbers, and you can't cast to string either.

`var node = createNode("textarea").attrs({ value: 123 }).renderToDom();`

Not fully tested, but seems to be same issues with: `buttons`, `checkbox` and `radio`

Have a look here too see different edge cases:  
https://github.com/ractivejs/ractive/tree/dev/src/virtualdom/items/Element/Attribute/prototype/update

**Comment by dfilatov** [comment]
I've tried this:
```js
vidom.mountToDomSync(
    document.body,
    createNode('textarea').attrs({ value : 123 }));
```
And have seen this:
![screen shot 2015-08-07 at 16 28 18](https://cloud.githubusercontent.com/assets/67957/9136717/7f259dc8-3d21-11e5-9002-99058a66f1d8.png)

What's wrong?

**Comment by dfilatov** [comment]
@rickardjanson ?

**Comment by rickardjanson** [comment]
@dfilatov Sorry. Not home at the moment. Issue occur in Internet Explorer. Older versions. In a few edge cases you have to set it as an attribue value. When I mention that, there are also an issue with `type` attribute in IE. I will see later if I can find some references, but for now I suggest have a look in the jQuery source code for valHooks.

**Comment by rickardjanson** [comment]
@dfilatov This is not my computer, but to answer you better. I just remember how we did it before with Internet Exolorer 10. We did'nt cast to string, but used `.toString()` to force it to be a string and then set as a property.

**Comment by rickardjanson** [comment]
Here is a few other issues I remember now:

- In `Windows Web Apps (WWA)` a radio button loose it's state if the name are set.

-  IE sometimes fails to persist the checked state of a cloned checkbox, or a checkbox that become something else. E.g. checkbox to radio button

**Comment by dfilatov** [comment]
I've tried in IE9:
```js
vidom.mountToDom(
    document.body,
    createNode('textarea').attrs({ value : 123 }));
```
And everything has worked as expected so I'm closing this issues.
If you have certain non-working cases please create separate issue. But please check before.
