### ISSUE TITLE
ForceUpdate, set and replace state?

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#93]
Should you add a method for forcing updates, and setting and replacing a state? Same as in REACT?

https://facebook.github.io/react/docs/component-api.html#setstate
https://facebook.github.io/react/docs/component-api.html#replacestate
https://facebook.github.io/react/docs/component-api.html#forceupdate

**Comment by dfilatov** [comment]
Not, I'm not going to adopt state concept from react inside engine.
