### ISSUE TITLE
text nodes are only child, not parent

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#94]
After checking you code a little, I figure out that text nodes are only children. They are not a parent of anything.  Even your `mount()` in `the TextNode` are a empty function. So you don't even have to try to use `mount()` on text nodes.

When I discovered this, I found out:

1. In the `appendChild()` function, you are rendring both `TagNode` and `TextNode`, but actually you only need to `renderToDom()` the `TagNode`. `TextNode` are already attached to it - rendered. 
This again would help you stop doing `renderToDom()` to much in the patching algorithm.
To prove it, just set a temporary `if` there and avoid inserting and render if it's text node. The code works just fine!!
As you also may notice for the `insertChild()` method, there are never a `TextNode` to be inserted. It's always a `TagNode`

2. in the patch method for the TextNode, you are checking `type` against `type`. This is code will never be executed. Just do a `console.log` on it, and it will return nothing.

3.  why do you want to set current parent namespace for a `TextNode`? It will not help you, a text is `nodeType 3` and can't be attached to anythng then text.

4. Again for the patching part for the `TextNode`. It will be better performance if you use `textContent` if the node are attached to it's parent, and `nodeValue` the other way around.

**Comment by dfilatov** [comment]
> TextNode are already attached to it - rendered. 

How is text node already attached? I can't understand how node can be attached without appending to its parent?

> in the patch method for the TextNode, you are checking type against type. This is code will never be executed. Just do a console.log on it, and it will return nothing.

Just try to patch `createNode('div').children(createNode().text('text'))` with `createNode('div').children(createNode('span'))` and you'll see code is executed.

> why do you want to set current parent namespace for a TextNode? It will not help you, a text is nodeType 3 and can't be attached to anythng then text.

Seems you're right. I'll find out and fix it.

> Again for the patching part for the TextNode. It will be better performance if you use textContent if the node are attached to it's parent, and nodeValue the other way around.

I don't understand. How is using `textContent` or `nodeValue` related to the fact of attaching  to its parent.

**Comment by rickardjanson** [comment]
Regarding `textContent` and `nodeValue` is all about optimization. If the node are attached to DOM, it's faster to use `textContent`. If the node are not attached to DOM, it's faster to use  `nodeValue`.  Say you are comparing two text nodes before using  `appendChild`, then the node are not attached yet, and  `nodeValue` are the optimal one to use.  After `appendChild`, `textContent` are the method to use.
**To say it simple so you avoid bugs in the future:**

`The text portion of a node is actually a child of the node itself. If a node has no data in it, such as then a call to childNodes[0].nodeValue will fail. You need to check for how many childNodes are actually present before you attempt to access them. `

*Therefor* use `textContent` on attached nodes, and `nodeValue` on non-attached nodes because they have no children etc.

For the `appendChild()` method, just try it. Try to avoid render a text node, and you will see it still works.

I see you example, and why `type` now give a meaning :)

**Comment by dfilatov** [comment]
> comparing two text nodes before using appendChild
There's no user way to compare nodes before they attached to DOM.

> For the appendChild() method, just try it. Try to avoid render a text node, and you will see it still works.
If I avoid rendering of a text node what I should append to its parent DOM node?

**Comment by rickardjanson** [comment]
I know there is no user way, I just wrote what gives best performance over all.

That is the strange thing, what you should append it to. Because it will still work if you test what I wrote. Maybe a bug, then?  Or maybe it's allready appended through the mount() function in TagNode?

**Comment by rickardjanson** [comment]
@dfilatov  I tried to figure it out, but there are a few other things I don't understand either. 
See this line here: 
https://github.com/dfilatov/vidom/blob/master/lib/client/patchOps.js#L7

You want to mount the children.

 So have a look at this line:
https://github.com/dfilatov/vidom/blob/master/lib/nodes/TagNode.js#L80-L91

if this node are a `TagNode`, this function will do the same thing. Call `mount()` on the child nodes to attach.

Further. In the `TextNode` your mount does nothing:
https://github.com/dfilatov/vidom/blob/master/lib/nodes/TextNode.js#L34

So what are you actually mounting here? First round of mount if `TagNode`, is to mount the children, but the children doesn't have a `mount()`

**Comment by dfilatov** [comment]
`mount()` isn't for attaching child nodes. It's not for dealing with DOM operations.

**Comment by rickardjanson** [comment]
So why have reduntant iteration there that does nothing then call itself, or a child that only have empty function when you do DOM operations?

**Comment by dfilatov** [comment]
Because all type of nodes should have common interface to get rid of redundant duck type checking.

**Comment by dfilatov** [comment]
> why do you want to set current parent namespace for a TextNode? It will not help you, a text is nodeType 3 and can't be attached to anythng then text.

I have investigated and haven't found where I set "current parent namespace for a TextNode". Could you point?

**Comment by rickardjanson** [comment]
So if you have a iteration loop that iterate through all nodes and only find a empty function, I think that will have impact on the performance. And the creation process.

You are not directly setting it:  https://github.com/dfilatov/vidom/blob/master/lib/nodes/TextNode.js#L28-L29

Anyhow. Compare with this solutions:

https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Text.js#L17-L22

Same as yours, and parent nameSpace are kept if you digg into the code.

**Comment by dfilatov** [comment]
parent is set not to keep its ns, it is set to make possible "replace" operation. See https://github.com/dfilatov/vidom/blob/master/lib/nodes/TextNode.js#L43

What about https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Text.js#L17-L22. As I have already written many times, in vidom it's impossible sutiation because user isn't dealing with render process, user can't call `renderToDom` directly. It's not a part of user interface.

**Comment by rickardjanson** [comment]
The line I was linking to in your code. Comment out the parent check, and run test cases again. Can you tell me why the tests didn't break?

**Comment by dfilatov** [comment]
> The line I was linking to in your code. Comment out the parent check, and run test cases again. Can you tell me why the tests didn't break?

Because there's no such test. I'll add it.

**Comment by rickardjanson** [comment]
Aha!

**Comment by rickardjanson** [comment]
Check this jsPerf for performance ideas.  And see how they do it. Just to give you ideas!

*.clonNode(true)*
http://jsperf.com/clonenode-vs-createelement-performance/55

**Comment by dfilatov** [comment]
Now vidom uses cloneNode for creating DOM nodes.
