### ISSUE TITLE
Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#95]
I tried to patch this:

``` 
 var node1 = createNode("div").children("baz");
  var node2   = createNode("span").children("bar foo");

 var domNode = node1.renderToDom();

node1.patch(node2)

```
Expected result:  The patched result not equal to domNode

**Comment by dfilatov** [comment]
I need full code. Patch can be applied before rendering.

**Comment by rickardjanson** [comment]
Updated the example code

**Comment by dfilatov** [comment]
`node` has no method `render`.

**Comment by rickardjanson** [comment]
Updated. I created a sub-function to test why it was not working.

**Comment by dfilatov** [comment]
You must attach you virtual tree to DOM before patching.
