### ISSUE TITLE
killed Firefox, and benchmark don't work in FF

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#96]
Hi. I tried your new changes, but in Firefox I a bunch of numbers followed by a *null*.
After a while FireFox dies.

Everything works just fine in Chrome.  But the overallTime are sky high!!

A good thing is that you got the creating down to under 400 in Chrome :+1:

**Comment by dfilatov** [comment]
> Ю in Firefox I a bunch of numbers followed by a null.

I understood nothing.

**Comment by rickardjanson** [comment]
Sorry. Your new changes works just fine in Chrome IF I run the benchmark, but the overallTime are around **53558** compared to **7834** for Inferno

In Firefox it doesn't render the nodes it seems: `226292 null` and the number getting higher and higher in Firefox until it goes empty for memory, my browser freeze and dies! 

In Webkit & Chrome, you also have a few other issues on my computer in the benchmark.

`[500] ["removeLast(500)"] update()	10325`

Should be around `99` as it was before not over `10 000`

Same with this

`[500] ["removeLast(250)"] update()	5249`

This one was around `77` before and now over `5000`

**Comment by rickardjanson** [comment]
This one is also a issue in Chrome

`[5,100] ["removeLast(1)","skip"] update()	1949`

Should be around `70` and not close to `2000`

**Comment by dfilatov** [comment]
Here is screenshot of benchmark in Chrome compared with cito.js you're always writing about:
![screencapture-localhost-3000-1438950788684](https://cloud.githubusercontent.com/assets/67957/9135804/da514240-3d19-11e5-9c61-7141a4a1d4f6.png)

So I don't understand what you mean by "sky high".

**Comment by dfilatov** [comment]
In firefox:
![2015-08-07 15 37 49](https://cloud.githubusercontent.com/assets/67957/9135882/7ced00c0-3d1a-11e5-8f5c-500b91d2441a.png)

**Comment by dfilatov** [comment]
So I have no idea what problems you're writing about in firefox.

**Comment by rickardjanson** [comment]
Ok. I see it works for you, but not on my computer. Or not my neighbours. 

But as long as it works just fine on your computer, I guess it's not an issue for you. I also now asked a few people to check this on their PC and Mac, and in Mac it worked just fine. On Ios9 beta it was a issue.

My main computer btw are using 32 GB DDR4 RAM and a 8x CPU, so should handle it.

**Comment by dfilatov** [comment]
I tried to run tests in Firefox on PC and Mac. Everything was ok, no errors.
Probable you're running tests wrong?
